name: browser_signer
description: A retro Dart web application for APK publishing with Nostr integration
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2

  crypto: ^3.0.3
  yaml: ^3.1.2
  http: ^1.1.0
  path: ^1.8.3
  bech32: ^0.2.2

dev_dependencies:
  lints: ^2.1.1